### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by vnlovers** [thesupersonic16/DALTools#1]
Will you consider to add new feature like dump script for .bin files for translation to another language?

**Comment by thesupersonic16** [comment]
I don't think I will beable to as I don't even fully know what scripts do and what to expect to see in them.

**Comment by vnlovers** [comment]
Maybe you will help this people,  because he try to translate this game but have problem [https://www.zenhax.com/viewtopic.php?f=12&t=12308&sid=640e13bbf56a8aa0f7e71fc2d529b089](url)

**Comment by vnlovers** [comment]
but if you can't then its alright

**Comment by thesupersonic16** [comment]
I have taken a look at the scripts, its all bytecode and its resources at the end. I have figured out some of the functions, but there is still a lot more work that needs to be done.
I have attached a file of a small script I tried to dissemble. Its pretty messy due to the tool being incomplete.

[test.txt](https://github.com/thesupersonic16/DALTools/files/3439223/test.txt)

**Comment by vnlovers** [comment]
> I have taken a look at the scripts, its all bytecode and its resources at the end. I have figured out some of the functions, but there is still a lot more work that needs to be done.
> I have attached a file of a small script I tried to dissemble. It is really messy and inaccurate due to the tool being incomplete.
> 
> [test.txt](https://github.com/thesupersonic16/DALTools/files/3439223/test.txt)

Looking forward to it! It will help the others. Good luck for complete this tool.

**Comment by thesupersonic16** [comment]
Rewrote the whole program to make editing alot easier. This is what I got so far.

[start01.txt](https://github.com/thesupersonic16/DALTools/files/3451815/start01.txt)

**Comment by vnlovers** [comment]
<img width="464" alt="error 2" src="https://user-images.githubusercontent.com/43198042/62336489-b0a5f280-b4fa-11e9-99b5-bc2a0f23ffac.png">
<img width="721" alt="error 1" src="https://user-images.githubusercontent.com/43198042/62336490-b0a5f280-b4fa-11e9-9457-860bd2e59de0.png">

**Comment by thesupersonic16** [comment]
What file were you dissembling?

**Comment by thesupersonic16** [comment]
Try this. currently the tool doesn't know all the codes. and I not even fully sure if I got them right.

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/3459505/DALTools.zip)

**Comment by thesupersonic16** [comment]
It's been a week now. Can you please tell me if you still have the issue or not?

**Comment by vnlovers** [comment]
> 
> 
> What file were you dissembling?

day01_mp1, day01_mp2, day04_ORIGAMI2, day04_ORIGAMI5, day02_TOUKA0, day05_TOUKA0c

**Comment by thesupersonic16** [comment]
Thanks, I will take a look at them.

**Comment by thesupersonic16** [comment]
I have taken a look. and have added the missing instructions.

[STSCTool.zip](https://github.com/thesupersonic16/DALTools/files/3511794/STSCTool.zip)

**Comment by vnlovers** [comment]
Ah, one file left that failed to dissasembling. It's 602_14_02.bin

**Comment by thesupersonic16** [comment]
[STSCTool.zip](https://github.com/thesupersonic16/DALTools/files/3512562/STSCTool.zip)

**Comment by vnlovers** [comment]
Thanks. All the scripts now can be extract from .bin to .txt files. But for translation it's not comfortable. I hope you're able to fix that issues.

**Comment by thesupersonic16** [comment]
Sorry I don't know anything about VN translation. What exactly is uncomfortable? Guessing its because it looks like there is a lot going on?
