### ISSUE TITLE
[PCKTool] Failing to extract .pck files with zlib

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#10]
https://www.dropbox.com/s/272h749jy9knwh1/MA140110.pck?dl=0
https://www.dropbox.com/s/iyytcl3llycr001/MA150110.pck?dl=0

First of all, thank you very much for this tool.

There is an error while trying to edit your PCK file.

The content of the error is:

처리되지 않은 예외: System.ObjectDisposedException: 닫혀 있는 파일에 액세스할 수 없습니다.
   위치: System.IO.__Error.FileNotOpen()
   위치: System.IO.FileStream.get_Position()
   위치: DALLib.File.PCKFile.Load(ExtendedBinaryReader reader)
   위치: DALLib.File.FileBase.Load(Stream stream, Boolean autoDecompress)
   위치: DALLib.File.FileBase.Load(String path, Boolean keepOpen)
   위치: PCKTool.Program.Main(String[] args)

**Comment by thesupersonic16** [comment]
Thanks for trying out DALTools. I have found the issue you have reported and fixed it.

Please download the release below and let me know if it resolves the issue you got.

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/3743072/DALTools.zip)

**Comment by shun9092** [comment]
Thank you !

It work perfect !

**Comment by thesupersonic16** [comment]
Great, Hope everything else works out perfectly for you. If you have any other issues, Please open a new issue. Closing
