### ISSUE TITLE
After modifying the background image and repacking, it is forced to shut down.

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#11]
After modifying the background, I ran to check the output.

But it is forcibly terminated in the background loading section.

The modified background is "MA069001.pck" in "DATE ​​A LIVE Rio Reincarnation \ Data \ Data \ Ma \ 1st".

Here are the original and modified files.

Original: https://www.dropbox.com/s/amqu4y02yb253ny/MA069001~.pck?dl=0

Fixed: https://www.dropbox.com/s/wog041e68qjaj8q/MA069001.pck?dl=0

The size of the capacity increased while modifying the PCK file.

We simply modified the script to see the output.

https://www.dropbox.com/s/h8dmpcq0xhudspy/day07_RINNE1e.bin?dl=0

https://www.dropbox.com/s/v6bic00gaovh418/start01.bin?dl=0

In line 68 of the "start01.bin" script, there is a section called "BgOpen (301, 0)".

Copy the contents of line 68, "BgOpen (0x1010D89, 0)", into the script "day07_RINNE1e.bin" and paste it into line 68 of "start01.bin".

However, the script loads nicely but is forced to exit when the background is loaded.

Perhaps in my opinion, you should modify "BgOpen (0x1010D89, 0)".

But there is no information about this.

I have a lot of things to change these background image files.

https://github.com/thesupersonic16/DALTools/blob/master/FUNCTIONS.md

I checked here, but there was no information on "BgOpen".

Do you know about this?

I need your help.

**Comment by thesupersonic16** [comment]
I just took a look at the code and when BgOpen is called it loads a file from `/Data/Bg/BGXXXX.tex` XXXX being the number in the in the parameters. I'm not entirely sure what you mean with the Ma files, They are CG files.

Can you please explain what you are doing? because they don't connect.

**Comment by shun9092** [comment]
I want to import the modified "MA069001.pck" in "DATE A LIVE Rio Reincarnation \ Data \ Data \ Ma \ 1st".

You can find this image in the "day07_RINNE1e.bin" file.

However, if you modify the file and run the game, it will be forcibly terminated.

To confirm, I renamed "start01.bin" to "day07_RINNE1e.bin" and "day07_RINNE1e.bin" to "start01.bin".

**Comment by shun9092** [comment]
So, simply

I want to modify files such as "MA069001.pck" in the "DATE A LIVE Rio Reincarnation \ Data \ Data \ Ma \ 1st" folder.
(I want to modify the files in the "DATE A LIVE Rio Reincarnation \ Data \ Data \ Ma \" folder.)

And I want to load in the game.

**Comment by thesupersonic16** [comment]
Sorry my bad, but I still don't know why you would rename the script.
Also I did find an issue in the packer while looking at the file you sent. I haven't tested this outside of the MA file you sent, but it fixed the issue with loading the CG.


[PCKTool.zip](https://github.com/thesupersonic16/DALTools/files/3800574/PCKTool.zip)

**Comment by shun9092** [comment]
Thank you, it work.

so, now I'm gonna check like every those files.

If I find the some issue, I'll tell you.

Thank you very much.

**Comment by thesupersonic16** [comment]
Cool, hope your project goes well.

**Comment by shun9092** [comment]
There are questions.

I want to do a batch job by creating a ".bat" command file.

But I have to drag and drop folders in case of pcktool.

So I don't know how to make

Do you know how to make a command?

**Comment by thesupersonic16** [comment]
For all files:
```
for %%i in (*.pck) do PCKTool "%%i"
```

For all directories:
```
for /d %%i in (*) do PCKTool "%%i"
```

**Comment by shun9092** [comment]
I have a question.

Can I add a page of a novel?

If you look at the 1ST page of the novel data, it's page 51.

I'd like to add a page. Is it possible?

**Comment by thesupersonic16** [comment]
It appears you can.

[ScriptDatabaseEditor.zip](https://github.com/thesupersonic16/DALTools/files/3817452/ScriptDatabaseEditor.zip)

Btw is your previous issue solved? If it is then you can close this issue thread.

**Comment by shun9092** [comment]
D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\PCKTool>PCKTool.exe NovData

처리되지 않은 예외: System.Collections.Generic.KeyNotFoundException: 지정한 키가 사전에 없습니다.
   위치: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   위치: DALLib.IO.ExtendedBinaryWriter.FillInOffset(String name, UInt32 value, Boolean absolute, Boolean removeOffset)
   위치: DALLib.File.PCKFile.Save(ExtendedBinaryWriter writer)
   위치: DALLib.File.FileBase.Save(Stream stream)
   위치: DALLib.File.FileBase.Save(String path, Boolean keepOpen)
   위치: PCKTool.Program.Main(String[] args)

=======================================

Repacking Error

**Comment by shun9092** [comment]
I want to add the number of novel files.

Because in translation, the number of characters increases, so I need to add a file.

There are 51 files in the 1st folder.

But translating requires more than 51 files.

Can I add more files?

**Comment by thesupersonic16** [comment]
Yeah you can add more files, I have tried it myself and the game loaded them just fine as long as they are sorted which I made a option to do that in the editor. Also for the PCPTool, are you using the one from the release? I used the one from the release and was able to pack them just fine. The one I gave you the other day had a mistake with packing files with folders.

**Comment by shun9092** [comment]
Sorry, I can't understand what u did.

If you have a 'discord', can I ask you here?

**Comment by thesupersonic16** [comment]
I do have a Discord, But I prefer to chat over here for issues with DALTools. 

Here is all the updated tools:
[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/3818439/DALTools.zip)

Anyways, Here is some steps for adding a page to the art book
1. Add all the page textures to your NovData and NovThumb archives
2. Open ScriptDatabaseEditor and load the database.bin file
3. Go to Art Book and right click the list of pages
4. Click Add Page
5. Ignore the `Page ID` as it will automatically be set later on
6. Set the `Game` field to whatever game the art book is for
7. Set the Page number in the `Page No` field
8. Enter a name of the page into `Page Name`
9. For both `Thumb Path` and `Data Path` click on the `...` button and select the texture file
10. Click Save
11. Right click the list of pages and then click `Sort Pages`

**Comment by shun9092** [comment]
It work well.

you can close this issue.

thank you very much!

**Comment by shun9092** [comment]
would you please publish current version?

**Comment by thesupersonic16** [comment]
Great, I just published it. Hope everything goes well with your translation project, and feel free to open a new issue if you have any questions or issues. I'm happy to help.

Closing.
