### ISSUE TITLE
There seems to be a problem using "STSTool"

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#12]
There seems to be a problem using "STSTool".

I'm not sure if this is the problem or not.

With "EnableMonologue (false)" the text box is invisible and you can print text.

You want to modify "Mes (Byte: positionX, Bool: centerX, Byte: positionY, Bool: centerY, String: text, Int16: messageID)".

Modify the "Byte: positionX" part to "0".

Or modify it to a random number, perhaps 0-200.

This modification aligns the text to the center.

But if you modify it, it won't apply

Please confirm.

This file is modified but not applied.
https://imgur.com/3Eqgklj
https://www.dropbox.com/s/lcy3cjwqdc21ocu/0_debug_12-tr.bin?dl=0

This is the original file.
https://www.dropbox.com/s/f7j2ki0t3s48fhe/0_debug_12.bin?dl=0

This is the original file.
https://www.dropbox.com/s/wnej61xmuwjpkd6/day07_KURUMI1e-tr.bin?dl=0

This is the file that you modified, which applies.
https://imgur.com/kYJZI3x
https://www.dropbox.com/s/ja90a001ype7ysl/day07_KURUMI1e.bin?dl=0

Please confirm.

**Comment by thesupersonic16** [comment]
Thanks for letting me know about this issue, As what you thought it is incorrect, 
It's actually `Mes(Int16: positionX, Int16: positionY, String: text, Int16: messageID)`

The Mes command only centres on the X axis from what I can see, But with some simple calculation you can make it centre on the Y axis. Note that the unit is 2/1 so 10 is 20 pixels on a 1920x1080 screen 
The Image below is 
`Mes(0, 231, "\"I like you\nbetter than a sea slug.\"\n - Fuko", 32)`
![DATE_A_LIVE_RIO-REINCARNATION_2019-11-05_13-00-51](https://user-images.githubusercontent.com/25761885/68172674-8b7ac180-ffcc-11e9-91eb-38fe802db017.png)

I will update the repo soon, here is the updated tools, please let me know if this solves your issue.
[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/3806931/DALTools.zip)
Please keep in mind that you will need to build all the disassembled scripts with the old version then disassemble them again with the new STSCTool.

**Comment by shun9092** [comment]
I repacked the old version as you said, and unpacked the new version.

However, if the encoding is a problem, the output is as shown below.

https://imgur.com/3rkrehw

**Comment by thesupersonic16** [comment]
If it detecting the file as UTF-8?

**Comment by shun9092** [comment]
Yes. I have checked all of the encodings but they all output strangely.

**Comment by thesupersonic16** [comment]
Does it work fine with a clean start01.bin?

**Comment by shun9092** [comment]
This is the file when you unpacked the original PCK and unpacked it using STSTOOL.
https://imgur.com/HWoJrOQ

This file is the file that you repacked with STSTOOL.
https://imgur.com/QtJJxWv

**Comment by thesupersonic16** [comment]
Mind redownloading the zip and unpack of of the bin files and send the .txt file to me so i can take a better look?

**Comment by shun9092** [comment]
original start01.bin
https://www.dropbox.com/s/1q61yiaigaujui6/start01-ori.bin?dl=0

unpacked start01.bin
https://www.dropbox.com/s/mw2duet8ds0j5q8/start01-ori.txt?dl=0

repacked start01.bin
https://www.dropbox.com/s/g1tltmo0bee89rt/start01-re.bin?dl=0

**Comment by thesupersonic16** [comment]
I'm not sure what is causing the issue. Maybe try this?
[STSCTool.zip](https://github.com/thesupersonic16/DALTools/files/3807227/STSCTool.zip)

**Comment by shun9092** [comment]
Good, when I drag n drop original file, it print clearly.

but, If I load a save, it crashed or load another(strange) scene.

**Comment by thesupersonic16** [comment]
Can you show me the crash?

**Comment by thesupersonic16** [comment]
Maybe forcing UTF-8 reading might fix it?
[STSCTool.zip](https://github.com/thesupersonic16/DALTools/files/3807258/STSCTool.zip)

**Comment by shun9092** [comment]
https://www.dropbox.com/s/tdyt27wtabyu2pq/DateALive_Rio_-20191105-133121-16136-3128.dmp?dl=0

**Comment by thesupersonic16** [comment]
oh I thought you meant the tool crashed.

Anyways did you try the version I sent 3 mins ago?

**Comment by shun9092** [comment]
I tried

It prints well.

However, the save fails to load and is forcibly terminated.

**Comment by thesupersonic16** [comment]
Can you send me the txt and bin file?

**Comment by shun9092** [comment]
Something twisted now.

If I find the problem again, I will write.

I'm not finding this problem right now.

I'll tell you if this happens again.

**Comment by shun9092** [comment]
Can you publish what we've talked?

There seems to be no problem now.

I'll tell it again if I see a save issue.

**Comment by thesupersonic16** [comment]
Great, I will soon. Closing.
