### ISSUE TITLE
Don't working DALTools

### ISSUE THREAD

**Issue by nik48** [thesupersonic16/DALTools#13]
I can't open code in Microsoft Visual Studio 2019:
8 errors:
CS0246 Cannot find type name or namespace "Scarlet" (no using directive or set reference?)
Project: DALLib File: TEXFile.cs
same with TEXConverters,CSC
2 warnings:
The component 'Scarlet' referenced was not found. DALLib
The referenced project '.. \ .. \ Scarlet \ Scarlet \ Scarlet.csproj' does not exist. DALLib
And i have question about file PrepareRelease.bat mkdir don't do anything and in folders bin i don't have folders Release (paths like: copy PCKTool\bin\Release\PCKTool.exe Release\PCKTool.exe don't even exist)
The most important thing for me is to translate the text from English to Polish.
Please help.

**Comment by thesupersonic16** [comment]
What method did you use to clone the repository? Since DALTools uses submodules you will need to use --recursive or manually clone the Scarlet repository.

Also the Releases are up to date currently you can use those if you don't need to edit the tools. If you are however editing the tools, mind tell me what you are planning to change? I might beable to help.

**Comment by nik48** [comment]
Ok. I check what i have in folders and when i downloaded files in .zip i unpacked them to folder, but folder Scarlet don't have files (it was empty). I downloaded this 1 folder from site https://github.com/TGEnigma/Scarlet/tree/8c56632eb2968e64b6d6fad14af3758e606a127d then i put thi in to folder with DATTools and it worked. I can use Font Editor,in PCKTool i have (screen 1), Script Database Editor is working,but most important Script Dialogue Editor show me this (screen 2),STSCTool show Error: Not Enough Arguments! STSCTool {.bin/.txt} and the last TEXTool show this (screen 3).I completely don't know about this program, so please explain to someone green
![1](https://user-images.githubusercontent.com/57587195/68548096-890fd180-03e9-11ea-80bf-58c2c99e7a9f.PNG)
![2](https://user-images.githubusercontent.com/57587195/68548099-8e6d1c00-03e9-11ea-8dcc-755f6c14b2ff.PNG)
![3](https://user-images.githubusercontent.com/57587195/68548100-90cf7600-03e9-11ea-8ffb-7c809ecfcb67.PNG)

**Comment by thesupersonic16** [comment]
Thanks for bringing this up. It appears I forgot to update a file `DALTools/ScriptDialogueEditor/STSCFileDialogue.cs`. 

I just pushed a new commit, Can you update your local repo and let me know if it fixes your issue?

> Can you say in what files is saved text to game if I would like to provide a translation in my country?
> This are only this 2 Script.pck and database.bin?

Sorry I do not understand what you mean for that part, All the text in game are in the Script.pck and database.bin

> TSCTool show Error: Not Enough Arguments! STSCTool {.bin/.txt} and the last TEXTool show this (screen 3).I completely don't know about this program, so please explain to someone green

STSCTool and TEXTool are CLI tools designed to have files dragged and dropped into it while also providing extra options for thoughs needing it through the command line.

**Comment by nik48** [comment]
Thanks for help it worked.
![1](https://user-images.githubusercontent.com/57587195/68577589-b0f64800-0470-11ea-986c-7ad9102d937d.PNG)


    Can you say in what files is saved text to game if I would like to provide a translation in my country?
    This are only this 2 Script.pck and database.bin?

Sorry I do not understand what you mean for that part, All the text in game are in the Script.pck and database.bin
That's exactly what I meant. Thanks.


    STSCTool show Error: Not Enough Arguments! STSCTool {.bin/.txt} and the last TEXTool show this (screen 3).I completely don't know about this program, so please explain to someone green

STSCTool and TEXTool are CLI tools designed to have files dragged and dropped into it while also providing extra options for thoughs needing it through the command line.
Thanks for explaining this STSCTool and TEXTool.
Everything is working now.

**Comment by nik48** [comment]
I looked again and opened by .exe and app showed my this:
Maybe it's bug? In Microsoft Visual Studio it's working.
![2](https://user-images.githubusercontent.com/57587195/68578363-21ea2f80-0472-11ea-96fe-19c008d48641.PNG)
![3](https://user-images.githubusercontent.com/57587195/68578369-23b3f300-0472-11ea-887a-79b4b82371c5.PNG)

**Comment by thesupersonic16** [comment]
So it works just fine on Visual Studio?

**Comment by thesupersonic16** [comment]
In your screenshot you are compiling to Debug. Maybe try switch to Release and press `Ctrl + Shift + B` to rebuild all the projects. From there you can use `PrepareRelease.bat` or just go into `DALTools/{PROJECT}/bin/Release/` and you should find the files you need. Also remember to copy any DLLs it produces along with the exe or else it will likly cause more issues.

Please let me know if this works or not.

**Comment by nik48** [comment]
Everything works. During the download, it does not save the release folders along with the files, but after adding all .exe with the DATLib.dll libraries and running, all work through .exe.
Thank you so much for help.

**Comment by thesupersonic16** [comment]
The repo is intentionally designed to not include the release with the code, Thats the point of the Releases page(Which I will update later).

Anyways I hope DALTools helps with your translation project.
