### ISSUE TITLE
[TEXTool] movie.tex not extracting properly

### ISSUE THREAD

**Issue by 4pull** [thesupersonic16/DALTools#14]
When I use TEXtool extract movie.tex, I get two files - movie.png and movie.xml. And movie.xml is extracted somehow incorrectly, because it lacks information about frames, unlike other similar files. Because of this, the screen Movie completely breaks.

**Comment by thesupersonic16** [comment]
Thanks for letting me know, I have pushed a possible fix for the issue. Currently I can not fully test the changes.

To get the update you can compile the new commit I just pushed or if you can not, I have also attached a release below

[TEXTool.zip](https://github.com/thesupersonic16/DALTools/files/3855634/TEXTool.zip) (Compiled with mono)

Please let me know if this resolves your issue.

**Comment by 4pull** [comment]
Yes! Now it works perfectly.
