### ISSUE TITLE
About dialogue window pop up

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#15]
Long time no see.

I have a problem while localizing, I will contact you.

I'm checking 2nd script and found a problem.

The script dialogue window does not appear in the original script, but the script dialogue window appears in the translated script.

The original and the script seem to be the same, but the output is weird.

Please check.

The script number name is "2nd / 002_00_00.bin".

original
https://imgur.com/VKOJjWm
pck
https://www.dropbox.com/s/ri850sk1a2j1muk/Scriptjp.pck?dl=0

Translation
https://imgur.com/sJJJteX
pck
https://www.dropbox.com/s/062l34anp16cwiq/Scriptkr.pck?dl=0

**Comment by thesupersonic16** [comment]
That's interesting, It even does it when you change it back to Japanese. 

<img width="641" alt="DATE_A_LIVE_RIO-REINCARNATION_2020-02-28_11-52-14" src="https://user-images.githubusercontent.com/25761885/75500412-f723e700-5a20-11ea-961a-bd6837a15668.png">

**Comment by thesupersonic16** [comment]
Oh I see, I have written the `EnableMonologue` instruction incorrectly. It isn't a bool it looks like to be some enum. I can update this, but it will break all already dissembled scripts.

**Comment by thesupersonic16** [comment]
Can you confirm if this solves your issue? You will have to start with a clean .bin. But if its a big deal, I can try make a simple editor for changing monologues manually.

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/4264896/DALTools.zip)

**Comment by shun9092** [comment]
I tried the program you created.

The output is normal.

It seems to work by manually changing the value of "EnableMonologue" to "0 or 1 or 2".

I will proceed with any other issues.

Thank you.

**Comment by thesupersonic16** [comment]
Yeah. `002_00_00` is meant to be set to `2`. So make sure that it is set correctly.

I will be closing this issue, if you do however run into another related problem, please feel free to reopen this issue and let me know. I am hoping to try make localisation easier for others to make.

**Comment by thesupersonic16** [comment]
Just posted the release I sent here as [1.11.3](https://github.com/thesupersonic16/DALTools/releases/tag/1.11.3)
