### ISSUE TITLE
Failed to enable live preview

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#18]
https://imgur.com/WteOZZX

Hi.

I contact you in case of problems while editing the script.

It doesn't work because the version of the game is different.

**Comment by thesupersonic16** [comment]
What version of the game do you have?

**Comment by shun9092** [comment]
My version is 1.00.02

**Comment by thesupersonic16** [comment]
Did you make sure the game is running with the filename containing `DATE A LIVE RIO-REINCARNATION` and is also on the same user?

By same user I mean if the game is running as admin, the editor will also need to be running as admin.

**Comment by shun9092** [comment]
It work. Thank you.

I running game as admin.

**Comment by thesupersonic16** [comment]
Great. I hope the feature will help, just keep in mind it's fairly buggy and is recommended to only edit lines that you are currently at in the game.
