### ISSUE TITLE
1st\nig_KANNAZUKI01.bin crash

### ISSUE THREAD

**Issue by 4pull** [thesupersonic16/DALTools#19]
Hello! I have a problem with this file. I translated the game into another language, but when in game I get to the text from this file, game crashes. I tried to replace this file with the original English version, but the result is the same - a crash after line 214. But it may not happen. This moment occurs on day 3, if you first meet with the Reine in Itsuka's house, and then go to meet with Kannazuki at the Tengu Tower. And another crash was again with this file, but in the second day (I can not say exactly when). Could there be something wrong with this particular file? Because there were no other crashes.
Of course, if you use the original Script.pck, there are no such crashes.

Here is my nig_KANNAZUKI01.bin, if needed. And if you need something else - I will provide it.
https://drive.google.com/open?id=1zeafcEaAITQF8mv7c_Gf3Y66pM6rhcF2
(reuploaded, wrong file)

**Comment by thesupersonic16** [comment]
There is something I actually need to know. And that's what language you translating from?

**Comment by thesupersonic16** [comment]
I'm assuming you are going from English since the English font includes the characters you are using and you are using spaces.

Also what do you mean about a crash after line 214? You talking about the file generated from STSCTool? If so this image below is the message after the line you mention. and doesn't seem to crash at all for me. (Line 214 is from Shido)

I'm also unsure what you mean with "if you first meet with the Reine in Itsuka's house", if there is a route I need to follow, please state clearly the options so I can reproduce it properly.

![image](https://user-images.githubusercontent.com/25761885/79400788-8df53480-7fca-11ea-9fd4-91f200eae7df.png)

**Comment by 4pull** [comment]
Yes, I was talking about file generated from STSCTool.

And about route. Not sure if it’s necessary to fully follow this route, but I followed Tohka's route, and on the third day after choosing Tohka's bento, I went to Itsuka's house(Reine), and then to Tengu tower(Kannazuki), where game crashes before the moment that was on your screenshot.

I tried to skip this moment using the original script, but in the end I ran into even bigger problems - crashes appeared on the map on the fourth day. I’m not even sure what exactly causes them. Because the game works great with the original script, but it refuses with mine, even if I replace the problem file with the original one. Just in case, I threw my script to you in private messages on Twitter (for some reason).

**Comment by thesupersonic16** [comment]
I see, it does crash there. But only if you do Reine before it.

**Comment by thesupersonic16** [comment]
I have the feeling the issue is related to 1st/day03_mp1 as replacing it with the English version fixes the issue on my end. At least with my rough testing.

**Comment by thesupersonic16** [comment]
Yeah, looks like using the English mp1 file seems to fix it. Not sure if you need it though. but a diff does show you translating the names. Maybe they are keys and not text that is seen in game.

**Comment by 4pull** [comment]
Yes, I changed the names on map. But I changed the first day map through the Dialogue editor, and the rest manually. Perhaps this is the problem. I will try to redo them through the editor and say whether this changed the situation!

**Comment by 4pull** [comment]
It worked! Changed all the names through Dialogue editor and no crashes.
