### ISSUE TITLE
.tex with ZLIB

### ISSUE THREAD

**Issue by imKota** [thesupersonic16/DALTools#2]
Hello, @thesupersonic16 
I try unpack Bg20000.tex

![image](https://user-images.githubusercontent.com/24241471/62432507-c99be700-b738-11e9-8ae1-6f495558bc00.png)

[Bg20000.zip](https://github.com/thesupersonic16/DALTools/files/3465579/Bg20000.zip)

**Comment by imKota** [comment]
and STSC too
![image](https://user-images.githubusercontent.com/24241471/62432604-534bb480-b739-11e9-9c77-fb35bcefa14a.png)

[database.zip](https://github.com/thesupersonic16/DALTools/files/3465590/database.zip)

**Comment by thesupersonic16** [comment]
Thanks for letting me know, I have added ZLIB decompression with zlib.net which means TEXTool can now decompress the files. For STSC, I will have to spend some time looking into how to get around this issue.


[TEXTool.zip](https://github.com/thesupersonic16/DALTools/files/3465811/TEXTool.zip)

**Comment by imKota** [comment]
@thesupersonic16 hmm.. one file don't unpack
[OPT_VOICE.zip](https://github.com/thesupersonic16/DALTools/files/3465819/OPT_VOICE.zip)

**Comment by imKota** [comment]
and this 
[1.zip](https://github.com/thesupersonic16/DALTools/files/3465845/1.zip)

**Comment by thesupersonic16** [comment]
Now it does.

Also all the files you sent me don't look like they are from DAL: RR at all. A Google search is giving me "Psychedelica of the Black Butterfly".

[TEXTool.zip](https://github.com/thesupersonic16/DALTools/files/3465920/TEXTool.zip)

**Comment by imKota** [comment]
> Also all the files you sent me don't look like they are from DAL: RR at all. A Google search is giving me "Psychedelica of the Black Butterfly".

Yeah ^^ 
But this work))

**Comment by imKota** [comment]
@thesupersonic16 Now I will try to unpack everything. And if something doesn’t unpack, I will throw off the file: 3

**Comment by imKota** [comment]
@thesupersonic16 252 files xD
https://dropmefiles.com/Iwo43

**Comment by thesupersonic16** [comment]
I see for STSC your game looks to use some older version. Not sure if the opcodes match. Gonna try quickly get it to disassemble.

**Comment by thesupersonic16** [comment]
Yep, The opcodes do not match. I have forcefully generated a txt with the scripts you sent so you can see what it couldn't disassemble. If you really need STSCTool to disassemble them, your best bet would be to fork the project and edit the instruction list to match with your game.

[00_07_002.txt](https://github.com/thesupersonic16/DALTools/files/3466722/00_07_002.txt)
[0_debug4.txt](https://github.com/thesupersonic16/DALTools/files/3466723/0_debug4.txt)
[database.txt](https://github.com/thesupersonic16/DALTools/files/3466724/database.txt)

**Comment by imKota** [comment]
@thesupersonic16 
> If you really need STSCTool to disassemble them, your best bet would be to fork the project and edit the instruction list to match with your game. I can tell you almost everything is different.


Let's do it :)
I forked your repository^^

**Comment by thesupersonic16** [comment]
I don't have the time to work on another game sadly. The only tips i can give you is look at the game's code, if its like DAL: RR theres an static array containing both names and functions for each opcode. and the functions return the new location( first param is added 1 before the call ) or try look at the script file and try make sense out of it. if you do not know how to basic reverse engineering, then I don't think you will get it done.

**Comment by imKota** [comment]
Ok, i will try :)
>I have forcefully generated a txt with the scripts you sent so you can see what it couldn't 
disassemble.

Can you tell how you generated them?
I would pull out the text and give it to the translator for translation

**Comment by thesupersonic16** [comment]
Please don't give the files I sent you to the translators, they are not build-able due to the amount of errors. Do you mind sending the exe so I can see if the interpreter works the same way?

**Comment by thesupersonic16** [comment]
Forgot to ask, is there any other issues with TEXTool? I shouldn't be keeping this issue open if the issue has been solved.

**Comment by imKota** [comment]
Hello, @thesupersonic16 
> Forgot to ask, is there any other issues with TEXTool? I shouldn't be keeping this issue open if the issue has been solved.

There are no other problems. Only the one that remains.

**Comment by thesupersonic16** [comment]
Sorry I can't help you with STSC as in this project I only support DAL: RR's scripts and since the TEXTool issue has been resolved I'll be closing this issue. Open a new issue if you have any other issues. And Thanks for letting me know textures could also use ZLIB compression.
