### ISSUE TITLE
About Ren Dystopia's files

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#24]
Hello. Long time no see.

I would like to request an analysis of the 'Ren Dystopia' game file.

The structure of the data is slightly different.

I don't think it's much different, and in the case of the tex file, there is a new header and the rest seems to be a png image.

Other than this, the structure is slightly different, can you analyze it?

https://drive.google.com/file/d/1IkK__mOCq4yl9VqESMUJrQgk8nUj7G90/view?usp=sharing

**Comment by thesupersonic16** [comment]
I have a little bit of progress on the scripts done but currently have not gotten much recently as I have been busy.

**Comment by thesupersonic16** [comment]
As for tex, it currently supports PNG but the latest release on GitHub does not. You will need compile the repo or wait for another release.

**Comment by shun9092** [comment]
So I need to wait?

**Comment by thesupersonic16** [comment]
Scripts are nowhere near complete and no idea when it will. I plan to sometime commit what I currently have. 
But for tex, you can try this

[TEXTool.zip](https://github.com/thesupersonic16/DALTools/files/6719734/TEXTool.zip)

**Comment by shun9092** [comment]
TEX file is work well !

But some files dosen't work

ex, 'Data\Init' folder's files

I'll have to wait for the script file. Thank you.
