### ISSUE TITLE
Character model tool availability?

### ISSUE THREAD

**Issue by Rezar0Fura** [thesupersonic16/DALTools#27]
So I used the given DALtools here for testing purposes. When I wanted to play with the character models, I tried to have them in my Photoshop, but the actual file containing the character sprites is this:

![tex_all](https://github.com/thesupersonic16/DALTools/assets/140922879/0e6bea5d-78ba-4394-8dba-28d16c7c3612)

I tried to solve this hell of a puzzle, but the results were horrible, to say the least. I know that it was intentionally made to compensate for the moving parts of characters in-game. But I think there could be a way to render the disfigured model in a said tool where their parts joined and showed as intended, where a selective frame could be used as a character picture model like this.
 
![6e1f8702-12e8-40ac-a3d5-f52afce6374c](https://github.com/thesupersonic16/DALTools/assets/140922879/5aedd9fe-b99a-4556-b437-fdbe6dea17e0)

Sorry if I dragged the request for too long, but In short, is there any way to have the desired character spirits into a normal-looking model?  Say if I wanted to use the character pictures for my own personal interest uses.

**Comment by thesupersonic16** [comment]
Oh nice, this is the first time hearing a MP viewer existing.

**Comment by Rezar0Fura** [comment]
Wow, thanks a lot @henrybode and @thesupersonic16, I wasn't expecting a quick reply. However, I have a few last doubts,

Is it possible to take the entire animation loop as one .gif or video file? The only method I could think of is to take all the frames and arrange them in another video software. But it would be filled with errors and kinda time-consuming.

I also came across the loop option, I thought it could be used to freeze the animation to help one take the required shot of a said frame only. While it could be taken regularly, it could be little reliable.

I also wondering if somehow there is an inbuilt feature where the site would take perfect cuts out of the character without requiring the user to manually fit the character on the screen and then take the picture.

All of these requests might sound demanding. But It's just asking for features which may be said to make "Life a bit easier."

Again, thanks for the original help thought. Cheers.

**Comment by Rezar0Fura** [comment]
I am currently looking for alternatives for recording for the first request, And I thought that the loop option is intended to stop or play the animation of a said character(My fault, sorry about it).

About the third point thought, I do not have any option which allows me to remove the left control panel, is it togglable? And about the browser's viewport, I tried fiddling with it but didn't get any likeable outcome. Can you help me with this?

**Comment by Rezar0Fura** [comment]
It works. I just had to do" ctrl+shift+c" after entering the inspect mode. Then I hover my mouse over the left control panel, as it would highlight the code page related in the elements tab in blue colour. I would right-click the options and grey background panel respectively and click the hide option, this may be better than entirely deleting and potentially ruining the code lines. All set.

Thanks again for the huge help. Appreciate it.

**Comment by Rezar0Fura** [comment]
> 
@henrybode.
Oh, What is it, I am hearing it for the first time. What does it do for my benefit? Could you explain?

Also, how do I make the "viewer" show this feature to me? (I am in doubt about what exactly you mean by a viewer and the steps to achieve the feature?)

**Comment by Rezar0Fura** [comment]
One last thing, how do I increase the resolution of the page? Like when I take photos of a character, it seems a little blurry. I was wondering if I could use any code help to increase the site's resolution, potentially fixing the average res shots problem. 

I just want to clarify that the photo taken is not trash nor a fault from my PC end, they are above something I wanted for working on a project involving these elements. I did my research like " increase the res of html5 canvas" and the obvious solution seems to increase the height and width pixel count in a constant ratio. I tried it, but it didn't help or just those Uncaught SyntaxError: Unexpected token '>'. Since I am not into the fields of codes and tech, I am clueless about the problem.

Since you are one tech guy, could you help me with the solution of increasing the page's resolution?

**Comment by Rezar0Fura** [comment]
Ok, I came through the solution. I will write down steps to help any future commer who came across this same problem.

1. You want to make your screen ratio 8k(7680 x 4320), having your selected model in optimal size fitting in the screen. [While this can noticeably lag the process, even for my low-end PC, it took a few extra seconds before doing the task perfectly. ]
![MPViewer - Brave 04-08-2023 02_47_04](https://github.com/thesupersonic16/DALTools/assets/140922879/202f5cb4-52ae-4513-bb3a-52974e1808bc)

2. We would choose "capture screenshot" option after clicking the 3 dots to see our available options, to take the image( For a low-end PC, again, it will seem as if it will crash, but it will a few seconds before taking a perfect screenshot.)

3. You want to trim the screenshot image[preferitially in a 1:1 square ratio] in any image editing software [I will be using Photoshop since it always makes sure of preserving the details we need for high res.], cutting the excess details like the blank grey background and the panel of options.
