### ISSUE TITLE
Tools supporting multiple files at once.

### ISSUE THREAD

**Issue by Rezar0Fura** [thesupersonic16/DALTools#28]
Can multiple files be selected at once and drag them directly into the PCK/TEXtool.exe to have all of them converted, instead of manually selecting each .pck/.tex file?

For game files containing folders like data/Ma/1st,2nd,3rd they have hundreds of files which is a pain to convert each one by one.

**Comment by thesupersonic16** [comment]
Might look into adding that next time the library is ready for a new release. For now I guess you could try using batch scripting?

**Comment by Rezar0Fura** [comment]
Okay, but what is it and how do I do that?

**Comment by thesupersonic16** [comment]
The way TEXTool handles commands are a bit complex to just take a bunch of files as args.

As for how to do it, this stackoverflow link may help. [link](https://stackoverflow.com/questions/14237548/batch-script-run-command-on-each-file-in-directory)

**Comment by thesupersonic16** [comment]
I can add it for PCKTool, just extract it in a folder containing DALLib.dll 
[PCKTool.zip](https://github.com/thesupersonic16/DALTools/files/12498970/PCKTool.zip)
