### ISSUE TITLE
Questions about other DATE A LIVE visual novels

### ISSUE THREAD

**Issue by bfloat16** [thesupersonic16/DALTools#29]
When I tried to use STSCTool to decrypt the bin file of Date A Live - Rinne Utopia, an error occurred (latest version，from Actions):
<img width="730" alt="image" src="https://github.com/thesupersonic16/DALTools/assets/38366253/e9676e9e-cf5c-4d26-9838-96983fcd1580">
The PS3 version of Script.pck is decrypted using make_npdata，and use PCKTool to unpack the bin file.
Is there any way to adapt the two PS3 versions of Date A Live: Rinne Utopia and Date A Live: Arusu Install?

**Comment by thesupersonic16** [comment]
Currently DALTools only supports Rio Reincarnation (including all three games), Ren Dystopia (with ScriptDialogueEditor) and one of the Psychedelica games.

The script files on the PS3 could possibly be simlar with a flipped endian. Can you upload the day scripts with anyone with link access?

**Comment by bfloat16** [comment]
Sure, here are all the script files：
https://drive.google.com/file/d/1YV0xB0pwN7vfR5OqUPTsli1k1DZNb3-x/view?usp=drive_link, https://drive.google.com/file/d/12iokc8rbYcw_IXir1xO4XyPInAGOd4nH/view?usp=drive_link

**Comment by Pantsu151** [comment]
Hello, what tool did you use to open the script.sdat? I am also trying to transfer the Spanish RU patch from PC to the PS3 version but I cannot decompile the files and recompile them.
![received_464467452679560](https://github.com/thesupersonic16/DALTools/assets/106005937/c0a47dcd-b642-4283-85b9-f1595d3b09f6)
