### ISSUE TITLE
STSCTool Cannot Disassemble database.bin

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#3]
is it work file "database.bin" ??

**Comment by shun9092** [comment]
https://www.dropbox.com/s/q0ghzdzltgwwyky/database.bin?dl=0

this is a "database.bin"

**Comment by shun9092** [comment]
The "movie.tex" file can be unpacked, but the lz77 compression does not work when repacking.

https://www.dropbox.com/s/2gq5aqduisv5ivr/movie.tex?dl=0

**Comment by thesupersonic16** [comment]
I did not notice that there was a database.bin in the Script folder. The file is very different from the ones in the Script PCK, but while it is still a STSC file, This file should be supported someday in the future. 
 
The code section in the file looks really small just DataBaseParam and Exit, But there is much more going on in the file like after the code seems to be an array of addresses to strings, then the strings themselves and much more. Not sure how to handle writing this to a more readable format at the end aswell.
 
I haven't taken a great look at the file, but it looks to be all related to the menu with a large chunk of it being the list of memories(Name, Desc, ID, Unknown) and its strings afterwards.

**Comment by shun9092** [comment]
Yes. Your right.
This file contains menus, options, and more.
Can you make a tool that can modify this file if possible?

**Comment by thesupersonic16** [comment]
Currently not, an not sure if I will make it work, Haven't decided yet.

**Comment by thesupersonic16** [comment]
So I have decided to make a new GUI tool to handle the database file. I am no where near finishing currently as there is still alot missing and I haven't even started writing the code for saving (Not sure how I will handle it currently).

This is a screenshot of what I currently have.

![image](https://user-images.githubusercontent.com/25761885/64939878-bfc3e280-d8a5-11e9-8c7c-f7fc0fa87333.png)

**Comment by shun9092** [comment]
updated?

**Comment by thesupersonic16** [comment]
Not yet, No where near being complete.

**Comment by shun9092** [comment]
oh, really? thank you!

**Comment by thesupersonic16** [comment]
Still nowhere being complete, Thought might be good to allow you to test it. Just drag the database.bin file into the exe.

[ScriptDatabaseEditor.zip](https://github.com/thesupersonic16/DALTools/files/3634640/ScriptDatabaseEditor.zip)

**Comment by shun9092** [comment]
Thank you.
It works fine, but there is a missing script.
0x15e22 ~ 0x15e45, Slight Affection Situation Rinne Ver
0x15e88 ~ 0x15e15e9c, Welcome Back, Master!
etc ...
The title of the drama CD is missing.

**Comment by shun9092** [comment]
And I'm localizing to the Japanese version.

**Comment by thesupersonic16** [comment]
I did not notice, I forgot to add the column. Here is an image of the tab with the Japanese database.bin

If you find any other major issues please let me know.

![image](https://user-images.githubusercontent.com/25761885/65332400-f2e9d700-dc01-11e9-8bb3-8a4d678fd1b8.png)

**Comment by shun9092** [comment]
is it possible to edit Drama CDs tab?
it need to edit Name.

https://imgur.com/0pBUfAh
and other issue.
in this case, Japanese version, but the image with name is output in English version.

**Comment by thesupersonic16** [comment]
There you go, Hope it works for you. Just make sure to backup regularly as I barely tested this.

Also just wondering, what language are you localising to?
[ScriptDatabaseEditor.zip](https://github.com/thesupersonic16/DALTools/files/3636722/ScriptDatabaseEditor.zip)

**Comment by shun9092** [comment]
I am localized in Korean. You have to create a new font and there are some difficulties.

**Comment by shun9092** [comment]
I am localized in Korean. You have to create a new font and there are some difficulties.

**Comment by shun9092** [comment]
https://imgur.com/ar4aWuc
It need a edit Voices Name tab.
I think it would be nice to be able to edit all tabs.
And than u should check last Voice Names tab
in game printed like その他キャラクター
but in program some different(その他キャラクタ：)

**Comment by thesupersonic16** [comment]
That's strange, It looks just fine on my end. And I guess I will work on getting Voice Names editable next.

![image](https://user-images.githubusercontent.com/25761885/65365440-a7184b80-dc5c-11e9-9682-0c8b12de5413.png)

**Comment by shun9092** [comment]
The character tab is a tab in which the name of the character is output when it is saved. In the case of the voice name tab, the character tab is output when the voice output is determined in the option.  It would be better if you modified it in all tabs.

**Comment by shun9092** [comment]
Okay.  I'm out now, so I'll post a screenshot later this evening.

**Comment by thesupersonic16** [comment]
Sorry, I do not understand what you just said. Characters is the list of characters in game that speaks, Voice Names is the list of characters in the options. Maybe the naming is confusing? If thats the case, I'm open for suggestions.

**Comment by shun9092** [comment]
Sorry.  I'm using Google Translator.  I'll upload it as a screenshot after I get home

**Comment by shun9092** [comment]
Uploaded in tab order
https://imgur.com/bmzBCic
https://imgur.com/ptp5pWb
https://imgur.com/vQKAeG7
https://imgur.com/oLFMY13
https://imgur.com/8PNOysc
https://imgur.com/bzzlI5l
https://imgur.com/1pk5wKy
https://imgur.com/zKG805j

This is an image with the character tab and voice tap applied.
We just modified the name to see how it is printed.
https://imgur.com/SUp8YNX
https://imgur.com/xMLPtWm

https://imgur.com/wmH3pH8
https://imgur.com/DKJhWpU

That's why I need to be able to edit all the tabs.

**Comment by shun9092** [comment]
Uploaded in tab order(from original database.bin)
https://imgur.com/bmzBCic
https://imgur.com/ptp5pWb
https://imgur.com/vQKAeG7
https://imgur.com/oLFMY13
https://imgur.com/8PNOysc
https://imgur.com/bzzlI5l
https://imgur.com/1pk5wKy
https://imgur.com/zKG805j

This is an image with the character tab and voice tap applied.
We just modified the name to see how it is printed.
https://imgur.com/SUp8YNX
https://imgur.com/xMLPtWm

https://imgur.com/wmH3pH8
https://imgur.com/DKJhWpU

That's why I need to be able to edit all the tabs.

**Comment by thesupersonic16** [comment]
You are not explaining the issue, and from what I see there is no issues. 
Is the names of the tabs confusing you? 
I can change them now if you like. I would prefer to not confuse anyone else in the future.

**Comment by shun9092** [comment]
If you look at the screenshot I modified below, you can see the name printed out.
But you can't modify it in a program. This is a file I created by simply modifying the hex code.

**Comment by shun9092** [comment]
The reason you need to modify the Name tab and the Voice tab is that the output is that way in the game.

**Comment by shun9092** [comment]
So I want to be able to modify all the tabs.
Sorry, I don't know why my reply is not to edit...

**Comment by thesupersonic16** [comment]
Seems to work just fine, I will send a newer version and try give you some basic instructions since you are using a translator.

[ScriptDatabaseEditor.zip](https://github.com/thesupersonic16/DALTools/files/3638849/ScriptDatabaseEditor.zip)

1. Click on the tab you want to edit
2. Double click on what you need to edit
3. Make your changes
4. Click "Save"
5. Then Click "Save" on the bottom
![image](https://user-images.githubusercontent.com/25761885/65376005-6b25ca80-dcde-11e9-8bd8-8b06bcf26e9b.png)

I have the feeling you are translating my messages and its not coming out right.
I just want to be sure we are not misunderstanding.

**Comment by shun9092** [comment]
You know how to use this program because you made it really good.

What I said is this updated version of the program you made right now.

I'm sorry for my poor English. It's really hard.

Thank you.

**Comment by shun9092** [comment]
I know how to use this program because you made it really good.

What I said is this updated version of the program you made right now.

I'm sorry for my poor English. It's really hard.

Thank you.

**Comment by shun9092** [comment]
This program probably doesn't have any problems modifying Database.bin.

If I have a problem or something that needs updating, I will tell you.

**Comment by shun9092** [comment]
This program probably doesn't have any problems modifying Database.bin.

If I have a problem or something that needs updating, I will tell you.

Perhaps I think this program is almost perfect right now.

**Comment by thesupersonic16** [comment]
Can you tell me what you have done in steps? So I can figure out the issue.
I want to beable to solve the issue.
Since we have a language barrier, I will try take this slow.

Where in the program do you first see a sign of something not working?
This can be things like:
- Names not updating
- No effect in game
- Nothing happening

**Comment by shun9092** [comment]
There is no problem right now.
I like it almost perfectly now.
If there's a problem or something to fix, I'll tell you.
Thank you very much.

**Comment by thesupersonic16** [comment]
Great, Hope everything works well for you.

**Comment by shun9092** [comment]
There is no problem right now.
I like it perfectly now.
If there's a problem or something to fix, I'll tell you.
Thank you very much.

**Comment by thesupersonic16** [comment]
I have pushed a new release with tool.

[Releases][daltool_releases_url]

[daltool_releases_url]: https://github.com/thesupersonic16/DALTools/releases

**Comment by thesupersonic16** [comment]
Forgot to close this.
Since the issue has been resolved, I will be closing this issue.
Please open a new issue if you have any other problems.
