### ISSUE TITLE
unable to find the installation folder.

### ISSUE THREAD

**Issue by Killer47x** [thesupersonic16/DALTools#30]
Hi,

When i launch the ScriptDatabaseEditor within the game folder it loads the database file, but then tells me
This feature requires DATE A LIVE: Rio Reincarnation to be installed

i have uninstalled it, Re-installed it but not sure why it still gives me the Message saying the game needs to be installed,
runs fine from my Steam client.

I got it installed on my D: drive
even tried moving via Steam to my C: drive and still get the same message.

**Comment by thesupersonic16** [comment]
I have updated the game detection code, you can download the artifact from [here](https://github.com/thesupersonic16/DALTools/actions/runs/8808195385/artifacts/1441292350).

Keep in mind CG exporting is broken with some of the complex CGs.

**Comment by Killer47x** [comment]
Thank you very much, its now working.
