### ISSUE TITLE
Can the tool be adapted to Rinne utopia and AInstall ps3?

### ISSUE THREAD

**Issue by Pantsu151** [thesupersonic16/DALTools#32]
I want to adapt the Spanish mod of Rinne Utopia from PC to the PS3 version.  but this one handles script.sdat.  Is there any way to extract this file that contains the game script on PS3?  
PD: The PC mod is compatible for the PS4 version, I already adapted it but I want to do the same with the PS3 ones but I don't know where to start.
![received_464467452679560](https://github.com/thesupersonic16/DALTools/assets/106005937/c5421d20-657f-4624-b5b9-56dcad2099eb)

**Comment by thesupersonic16** [comment]
I am not sure what the file format is for that nor if its encrypted. You could try sending the file and I might take a look.

**Comment by Pantsu151** [comment]
Here are some main files of ps3 rinne utopia folders:https://drive.google.com/drive/folders/1nUkxnqbULrga4eeF7YHInM_buh3E_y0t

Here is the script.sdat file, I think there are the conversations:https://drive.google.com/file/d/18I6tskuQ-dUL_VU03Wo2Q4OdVcQLq5Hw/view?usp=drivesdk

**Comment by thesupersonic16** [comment]
The file is likely a PS3 related file.  The file appares to follow the same file structure as [EDAT](https://www.psdevwiki.com/ps3/EDAT_files)[psdevwiki.com] which isn't exactly the focus of this project.

Looking into EDAT might help with figuring out the solution to your problem.
