### ISSUE TITLE
New .pck and tex ?

### ISSUE THREAD

**Issue by imKota** [thesupersonic16/DALTools#4]
Hello, @thesupersonic16 

can you add support this files?

[new pck and tex.zip](https://github.com/thesupersonic16/DALTools/files/3595713/new.pck.and.tex.zip)

**Comment by thesupersonic16** [comment]
Back with the non-DAL game files lol. I will take a look at them when I have time. but if I do add unpacking and repacking, I would have to add a switch for repacking for that game.

**Comment by imKota** [comment]
@thesupersonic16 Do you have a discord/telegram? If so, can you write it to me on my mail (aleksey-nyaka@yandex.ru). I would like to discuss something personally.

**Comment by thesupersonic16** [comment]
Got it to read the TEX and PCK files you sent. I haven't tested if it works for obvs reasons. Let me know how it goes, Just keep in mind that TEXTool writing will most likely not work currently.

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/3599688/DALTools.zip)

**Comment by imKota** [comment]
@thesupersonic16 Hmm.. nice 90% (.pck and .tex) of the files are unpacked. 
besides these
[dont unpack.zip](https://github.com/thesupersonic16/DALTools/files/3600316/dont.unpack.zip)

**Comment by thesupersonic16** [comment]
I was just looking at this, Can you tell me what game you got the files from?

**Comment by imKota** [comment]
Hello, @thesupersonic16 
Mary Skelter: Nightmares or Psychedelica of the Black Butterfly
