### ISSUE TITLE
script.pck repacked doesn't work ingame

### ISSUE THREAD

**Issue by Zapiboss** [thesupersonic16/DALTools#5]
Hello,

I'd be interested to translate this VN into french, so i did some tests :

- Extracted Script.pck with PCKTool.exe
- Extracted start01.bin with STSCTool.exe, this gave me a file named start01.txt
- Here, i tried to change the first sentence into french and I also tried without changing anything
- Dragged start01.txt (modified and untouched) back into STSCTool.exe, this gave me a new start01.bin (I deleted the .txt file now that i compiled it into a .bin file)
- Repacked Script.pck when i dragged the folder Script with PCKTool.exe

And, result :
![image](https://user-images.githubusercontent.com/4704947/65825404-c0ca1c00-e276-11e9-9177-cc8e4010150c.png)

This is strange that even when i didn't changed anything inside the file and repacked it, it didn't work.

Language for non-Unicode programs : Tested with French

Thank you in advance for your help !

**Comment by thesupersonic16** [comment]
I'm sorry to hear about your experiences with DALTools. Mind sending me the new Script.pck so I can inspect the issue?

**Comment by thesupersonic16** [comment]
I have found the issue, The cause was in PCKTool which I already fixed after refactoring. I have also fixed the indexing issue with the newer PCKTool so now it should create PCKs properly. 

[DALTools.zip](https://github.com/thesupersonic16/DALTools/files/3666444/DALTools.zip)

Please let me know if this solves your issue.

**Comment by Zapiboss** [comment]
Just tried with your updated tools :
![image](https://user-images.githubusercontent.com/4704947/65833039-ee8d8000-e2cb-11e9-9c8a-ab576fd4d60b.png)

You're a god dude, i'm glad i tried the tools while you're still here, working on that !
I'll let you know if there are any issues !

**Comment by thesupersonic16** [comment]
Great! Open a new Issue if you have any more issues. and I really hope you are able to achieve your goal  in translating the Visual Novel.
