### ISSUE TITLE
MapPlace instruction has wrong argument

### ISSUE THREAD

**Issue by Akintos** [thesupersonic16/DALTools#6]
First of all, thank you very much for creating this great tool.

Currently, instruction `MapPlace` has three arguments `new []{ AT_Int16, AT_Int32, AT_CodePointer })`

I think second argument should be `AT_String`, not `AT_Int32`

[day01_mp1.zip](https://github.com/thesupersonic16/DALTools/files/3695458/day01_mp1.zip)

I tried using STSCTool to disassemble this script file.

```
MapPlace(8, 1447, LABEL_0361)
MapPlace(5, 1460, LABEL_0231)
MapPlace(2, 1470, LABEL_02FF)
MapPlace(4, 1477, LABEL_01CA)
MapPlace(0, 1484, LABEL_02FA)
MapPlace(1, 1494, LABEL_01C5)
MapPlace(6, 1504, LABEL_0298)
MapPlace(3, 1520, LABEL_0236)
```
Second arguments of those instructions are the offset of strings.

![이미지 331](https://user-images.githubusercontent.com/11464653/66283616-21a0c680-e8ff-11e9-99a9-2e0fed9c0746.png)

`0x5A7 = 1447`

**Comment by thesupersonic16** [comment]
You are right it is a string, Thanks for the fix.
