### ISSUE TITLE
[ScriptDialogueEditor]

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#8]
SDE Info:
    Version: 1.0.0
    Args: 
    StartDir: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools-1.9.0\
    Process Level: User
    ScriptPath: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Data/ENG/Script/Script.pck

Exception:
    Type: InvalidOperationException
    Message: 응용 프로그램에 콘솔이 없거나 콘솔 입력이 파일에서 리디렉션된 경우 키를 읽을 수 없습니다. Try Console.Read를 사용하십시오.
    Source: mscorlib
    Function: System.ConsoleKeyInfo ReadKey(Boolean)
    StackTrace: 
       위치: System.Console.ReadKey(Boolean intercept)
       위치: DALLib.File.STSCFile.Load(ExtendedBinaryReader reader)
       위치: ScriptDialogueEditor.STSCFileDialogue.Load(ExtendedBinaryReader reader)
       위치: DALLib.File.FileBase.Load(Stream stream, Boolean autoDecompress)
       위치: ScriptDialogueEditor.MainWindow.LoadScript(String scriptName, Boolean save)
       위치: ScriptDialogueEditor.MainWindow.ScriptListBox_SelectionChanged(Object sender, SelectionChangedEventArgs e)
       위치: System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       위치: System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
       위치: System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
       위치: System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
       위치: System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
       위치: System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
       위치: System.Windows.Controls.Primitives.Selector.OnSelected(Object sender, RoutedEventArgs e)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       위치: System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
       위치: System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
       위치: System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
       위치: System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
       위치: System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
       위치: System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
       위치: System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
       위치: System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
       위치: System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
       위치: System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
       위치: System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
       위치: System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
       위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       위치: System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
       위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       위치: System.Windows.Input.InputManager.ProcessStagingArea()
       위치: System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       위치: System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       위치: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       위치: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       위치: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       위치: System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       위치: System.Windows.Application.RunDispatcher(Object ignore)
       위치: System.Windows.Application.RunInternal(Window window)
       위치: System.Windows.Application.Run(Window window)
       위치: ScriptDialogueEditor.App.Main(String[] args)
    InnerException: 

I opened it to modify the script, but suddenly I got this error

**Comment by shun9092** [comment]
is it possible to change language option??
there is no change language option like DatabaseEditor

**Comment by thesupersonic16** [comment]
Can you tell me what script you selected? and what you exactly did you create this error?

Also there isn't a need for a language option as nothing outside of the Script folder is loaded

**Comment by shun9092** [comment]
When I first ran it, the English script was loaded.
And when I checked the script alternately, it ended with an error.
If you select any script many times, it will exit with an error.

**Comment by shun9092** [comment]
When I first ran it, the English script was loaded.
When I first ran, I just ran the program with a double click.
To load the Japanese version of the script, I used drag and drop.
It would be nice if the script had a language selection option like DatabaseEditor.
And when I checked the script alternately, it ended with an error.
If you select any script many times, it will exit with an error.

**Comment by shun9092** [comment]
SDE Info:
    Version: 1.0.0
    Args: 
    StartDir: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools-1.9.0\
    Process Level: User
    ScriptPath: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Data/ENG/Script/Script.pck

Exception:
    Type: InvalidOperationException
    Message: 응용 프로그램에 콘솔이 없거나 콘솔 입력이 파일에서 리디렉션된 경우 키를 읽을 수 없습니다. Try Console.Read를 사용하십시오.
    Source: mscorlib
    Function: System.ConsoleKeyInfo ReadKey(Boolean)
    StackTrace: 
       위치: System.Console.ReadKey(Boolean intercept)
       위치: DALLib.File.STSCFile.Load(ExtendedBinaryReader reader)
       위치: DALLib.File.FileBase.Load(Stream stream, Boolean autoDecompress)
       위치: ScriptDialogueEditor.MainWindow.BatchExportTranslationMenuItem_Click(Object sender, RoutedEventArgs e)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       위치: System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       위치: System.Windows.Threading.DispatcherOperation.InvokeImpl()
       위치: System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       위치: MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       위치: MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       위치: System.Windows.Threading.DispatcherOperation.Invoke()
       위치: System.Windows.Threading.Dispatcher.ProcessQueue()
       위치: System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       위치: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       위치: System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       위치: System.Windows.Application.RunDispatcher(Object ignore)
       위치: System.Windows.Application.RunInternal(Window window)
       위치: System.Windows.Application.Run(Window window)
       위치: ScriptDialogueEditor.App.Main(String[] args)
    InnerException: 

===============
This error is output when executing Batch Export translation.
I selected and executed this option, but when I hit the save button, I get an error and exit.

**Comment by thesupersonic16** [comment]
So all you did was just run the program and Selected Batch Export Translation?

I can see its failing to read one of the scripts from the archive. Is the Script.pck you are working with clean? by clean I mean untouched.

**Comment by shun9092** [comment]
I used an archive that I modified.
I tried the original archive now and it seems to work fine without any errors.
This program seems to only load English scripts. Can I add options to read other language scripts?
If you add this option, it will be very helpful to localize.

**Comment by thesupersonic16** [comment]
All languages work perfectly fine for me. Here is what I have currently. I have added the language option that you asked. (Left it on the main window as I don't see this program needing a Options window)

[Release.zip](https://github.com/thesupersonic16/DALTools/files/3710843/Release.zip)

Just change the language and restart the program.
Please let me know if it works as expected.

**Comment by shun9092** [comment]
It seems to work well.
Thank you very much for adding the option I mentioned.
If I have another issue while using the program, I will tell you.

**Comment by shun9092** [comment]
It seems to work well.
Thank you very much for adding the option I mentioned.
If I have another issue while using the program, I will tell you.
Thank you very much.

**Comment by shun9092** [comment]
It seems to work well.
Perhaps you can upload these programs.
Thank you very much for adding the option I mentioned.
If I have another issue while using the program, I will tell you.
Thank you very much.

**Comment by thesupersonic16** [comment]
Great, I will publish them later. Hope you will find my tools useful :)
Also a tip when using GitHub, There is a Edit button, no need to post a new comment with the new edit.

![image](https://user-images.githubusercontent.com/25761885/66547292-9fc4cd80-eb8a-11e9-9ca8-e697f573e876.png)

**Comment by vnlovers** [comment]
I managed to export the .pck file to the .po files, but how do I insert text from .po to .pck?

**Comment by thesupersonic16** [comment]
The .po export/import isn't really tested as not many people use it. Anyways to import the .po file, you need to right click the script and press Import Translation and the text should appear and press Save*. The issue with the importing currently is that its all keyed, so it won't re-import already translated text. I could make a option to ignore keying so you re-import.

\* Due to a bug that I have already fixed but not released yet, After any edits to a file, you need to open a new script then press Save. On the next release you should beable to hit Save after you are done with your edits.
