### ISSUE TITLE
[ScriptDatabaseEditor]

### ISSUE THREAD

**Issue by shun9092** [thesupersonic16/DALTools#9]
SDE Info:
    Version: 1.0.1
    Args: 
    StartDir: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Kor\DALTools-1.9.0\
    Process Level: User
    GamePath: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation
    DataBasePath: D:\Program Files (x86)\Steam\steamapps\common\DATE A LIVE Rio Reincarnation\Data\JPN\Script\database.bin

Exception:
    Type: XamlParseException
    Message: 'System.Windows.Markup.TypeExtension'에 대한 값 제공에서 예외가 throw되었습니다.
    Source: PresentationFramework
    Function: System.Object Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
    StackTrace: 
       위치: System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       위치: System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
       위치: System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
       위치: System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
       위치: ScriptDatabaseEditor.PropertyEditorDramaCD.InitializeComponent()
       위치: ScriptDatabaseEditor.PropertyEditorDramaCD..ctor(DramaCDEntry entry)
       위치: ScriptDatabaseEditor.MainWindow.DC_ListView_MouseDoubleClick(Object sender, MouseButtonEventArgs e)
       위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       위치: System.Windows.Controls.Control.OnMouseDoubleClick(MouseButtonEventArgs e)
       위치: System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
       위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       위치: System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
       위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       위치: System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
       위치: System.Windows.Input.InputManager.ProcessStagingArea()
       위치: System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       위치: System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       위치: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       위치: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       위치: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       위치: System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       위치: System.Windows.Application.RunDispatcher(Object ignore)
       위치: System.Windows.Application.RunInternal(Window window)
       위치: System.Windows.Application.Run(Window window)
       위치: ScriptDatabaseEditor.App.Main(String[] args)
    InnerException: System.Xaml.XamlParseException: 형식 참조에서 이름이 '{clr-namespace:ScriptDatabaseEditor;assembly=ScriptDatabaseEditor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null}GameID'인 형식을 찾을 수 없습니다.
   위치: MS.Internal.Xaml.Context.ObjectWriterContext.ServiceProvider_Resolve(String qName)
   위치: MS.Internal.Xaml.ServiceProviderContext.System.Windows.Markup.IXamlTypeResolver.Resolve(String qName)
   위치: System.Windows.Markup.TypeExtension.ProvideValue(IServiceProvider serviceProvider)
   위치: MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)

**Comment by thesupersonic16** [comment]
Thanks for letting me know about the crash. Next time if possible you should include more information about the issue, I was lucky this report has enough information in the stack trace where you were when it crashed.

Please download the file below and let me know if it works.
[Release.zip](https://github.com/thesupersonic16/DALTools/files/3709459/Release.zip)

**Comment by shun9092** [comment]
Thank you.
DatabaseEditor seems to work fine without any errors.
If I find another issue, I will tell you.

**Comment by thesupersonic16** [comment]
Great, Open a new issue if you have any other issues.
